name: Publish Notification

on:
  push:
    branches:
      - main
      - web-push
    paths:
      - "apps/docs/src/routes/en-US/blog/index.json"
      - "apps/docs/src/routes/(ja)/blog/index.json"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0
      - name: Check for new published articles
        id: check-published
        run: |
          CHANGED_JSON_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.json$')
          for file in $CHANGED_JSON_FILES; do
              jq -c 'to_entries | .[] | select(.value.published == true) | {index: .key, value: .value}' $file | while read item; do
                  INDEX=$(echo $item | jq '.index')
                  ARTICLE=$(echo $item | jq '.value')
                  if [[ ! -z "$ARTICLE" ]]; then
                      echo "JSON_FILE_PATH=$file" >> $GITHUB_ENV
                      echo "JSON_INDEX=$INDEX" >> $GITHUB_ENV
                  fi
              done
          done
      - name: Send Notification
        if: env.JSON_INDEX
        run: |
          cd .github/workflows/publish-notification/
          npm install
          IFS=$'\n'
          for article in $JSON_INDEX; do
            node index.mjs "$article"
          done
        env:
          ONE_SIGNAL_API_KEY: ${{ secrets.PUBLIC_ONE_SIGNAL_API_KEY }}
          ONE_SIGNAL_APP_ID: ${{ secrets.PUBLIC_ONE_SIGNAL_APP_ID }}
